[versions]
retrofit = "2.9.0"
room = "2.6.1"
lifecycle = "2.3.1"

material = "1.9.0"
appcompat = "1.6.1"
coreKtx = "1.8.0"

hilt = "2.49"
androidxHilt = "1.0.0"

glide = "4.14.2"

junit = "4.13.2"
testJunit = "1.1.4"
espresso = "3.5.0"

firebaseBom = "31.2.0"
firebaseAuth = "21.1.0"
googlePlayServices = "20.5.0"

gson = "2.9.0"
okhttpLogging = "5.0.0-alpha.2"
kotlinxSerialization = "1.6.3"

kotlin = "2.0.20"
gmsMaps = "19.1.0"
workManager = "2.9.1"
startup = "1.2.0"

[libraries]

material = { module = "com.google.android.material:material", version.ref = "material" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidCoreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }


hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
androidxHiltCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHilt" }
androidxHiltWork = { module = "androidx.hilt:hilt-work", version.ref = "androidxHilt" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

junit4 = { module = "junit:junit", version.ref = "junit" }
testJunit = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebaseAuth = { module = "com.google.firebase:firebase-auth-ktx" } # version via BoM
firebaseAuthV = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuth" }
firebaseAnalytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebaseDatabase = { module = "com.google.firebase:firebase-database-ktx" }

googlePlayServicesAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "googlePlayServices" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitConverterMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofitConverterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLogging" }

roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }

kotlinSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
playServicesMaps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "gmsMaps" }
androidxWorkRuntimeKtx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
androidxStartupRuntime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }

[bundles]
room = ["roomRuntime", "roomKtx", "roomCompiler"]
retrofit = ["retrofit", "retrofitConverterMoshi", "retrofitConverterGson","okhttpLogging"]
daggerHilt = ["hiltAndroid", "hiltAndroidCompiler", "androidxHiltCompiler","androidxHiltWork"]


